### ISSUE TITLE
[BUG] 댓글 글자 수 오버플로우

### ISSUE THREAD

**Issue by highcastlee** [ZB-Online/TeamFinder#22]
## 스타일 이슈
- 자동 줄바꿈 적용 필요

![image](https://user-images.githubusercontent.com/62092665/146133734-0490a5e5-4b1d-4c27-9983-98be42c88170.png)

**Comment by chmini** [comment]
이 버그가 영어에만 해당이 되네요..
영어와 한글의 차이였습니다ㅋㅋㅋㅋ

요거는 링크해둔 pr에서 해결해두겠습니다
