### ISSUE TITLE
[BUG] 글쓰기 post 데이터 타입 변환

### ISSUE THREAD

**Issue by highcastlee** [ZB-Online/TeamFinder#23]
## 글 작성 시, city와 sportsType 데이터 타입
- API에 숫자 타입으로 사용되고 있으므로 post 보낼 때, 숫자로 타입 변환 필요
  - sportsType: num[]
  - city : num

![image](https://user-images.githubusercontent.com/62092665/146134696-5413e7ca-a5d0-40f0-86e5-d3877cdbfa44.png)
![image](https://user-images.githubusercontent.com/62092665/146134655-8db33122-a881-437b-8aa9-26b193972c03.png)

**Comment by yusonghyeon** [comment]
네 확인하고 수정했습니다. 상세 페이지 pr 보낼때 같이 보내겠습니다
